{
	"version": 1733143839,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bgmenu-sheet0.png",
		"images/play-sheet0.png",
		"images/bglevel-sheet0.png",
		"images/huruf-sheet0.png",
		"images/huruf-sheet1.png",
		"images/huruf-sheet2.png",
		"images/jawaban-sheet0.png",
		"images/tempathuruf-sheet0.png",
		"images/buah-sheet0.png",
		"images/buah-sheet1.png",
		"images/particles.png",
		"images/goodjob-sheet0.png",
		"images/next-sheet0.png",
		"images/sprite-sheet0.png",
		"images/level1-sheet0.png",
		"images/level2-sheet0.png",
		"images/level3-sheet0.png",
		"images/level4-sheet0.png",
		"images/home-sheet0.png",
		"images/save-sheet0.png",
		"images/load-sheet0.png",
		"images/tomboltanya-sheet0.png",
		"images/tanya-sheet0.png",
		"images/cancel-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/bling.m4a",
		"media/bling.ogg",
		"media/dreamy.m4a",
		"media/dreamy.ogg",
		"media/hello.m4a",
		"media/hello.ogg",
		"media/open up.m4a",
		"media/open up.ogg",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/a korean drama.m4a",
		"media/a korean drama.ogg",
		"media/introduce_and_daily_routine___yuni_1a_reguler__[_youconvert.net_].m4a",
		"media/introduce_and_daily_routine___yuni_1a_reguler__[_youconvert.net_].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}